---
title: "Assignment 5"
author: "Madeline Berger"
date: "2026-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rstan)
options(mc.cores = parallel::detectCores()) # set up to estimate your model in parallel
rstan_options(auto_write = TRUE) # automatically save a bare version of a compiled Stan program to the hard disk so that it does not need to be recompiled

library(rethinking)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(tidybayes)

```

## 4M1. For the model definition below, simulate observed y values from the prior (not the posterior).

*yi ∼Normal(µ, σ)*

*µ∼Normal(0, 10)*

*σ ∼Exponential(1)*

```{r 4M1}

set.seed(100)
N <- 1000
mu <- rnorm(N,0,10)
sigma <- rexp(N, rate = 1)

prior_y <- rnorm(N, mu, sigma)

dens(prior_y)

```

## 4M2. Translate the model just above into Stan code.

```{r 4M2, eval = FALSE}

write("// 

data {
 int < lower = 1 > N; // sample size
 vector[N] y; // response
}

parameters {
  real < lower = 0 > mu; 
  real < lower = 0 > beta; // where does sigma go?
}

model {
  y ~ normal(mu, sigma);
  mu ~ normal(0,10);
  sigma ~ exponential(beta);
}

generated quantities {
} 
",

"stan_4m.2.stan")


```
